project:
  type: default

format:
  revealjs:
    theme: moon
    transition: fade
    slide-number: true
    chalkboard: true
    preview-links: auto
    margin: 0.1
    width: 1050
    height: 700

execute:
  freeze: true
